version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  postgresdb:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_ROOT_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_LOCAL_PORT
    volumes: 
      - db-config:/etc/postgres
      - db-data:/var/lib/postgres
      - ./db/backup/files/:/data_backup/data
  app:
    build:
        context: .
        dockerfile: ./Dockerfile
    image: node-mysql-postgres-app
    depends_on:
        - mysqldb
        - postgresdb
    stdin_open: true
    tty: true
    environment: 
        MYSQL_HOST: mysqldb
        POSTGRES_HOST: postgresdb
    volumes: 
        - .:/app/
        - /app/node_modules

volumes: 
  db-config:
  db-data:
